<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Link renders a semantic anchor element.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";
  import type { LinkSize, LinkVariant } from "./link.shared";

  export type LinkProps = {
    variant?: LinkVariant;
    size?: LinkSize;
    href?: string;
    target?: string;
    rel?: string;
    external?: boolean;
    disabled?: boolean;
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { linkClasses } from "./link.shared";
  import { eqStr, isSetStr, orUndef } from "../../utils/expr";

  let {
    variant,
    size,
    href,
    target,
    rel,
    external,
    disabled,
    class: className,
    children,
    ...rest
  }: LinkProps = $props();

  const cls = $derived(linkClasses({ variant, size, disabled, className }));
  const targetValue = $derived((isSetStr(target) ? target : (external ? "_blank" : "")));
  const relValue = $derived((isSetStr(rel) ? rel : ((external || eqStr(targetValue, "_blank")) ? "noopener noreferrer" : "")));
</script>

{#if disabled}
  <a {...(cls ? { class: cls } : {})} aria-disabled="true" tabindex="-1" {...rest}>
    {@render children?.()}
  </a>
{:else}
  <a href={orUndef(href)} {...(cls ? { class: cls } : {})} target={orUndef(targetValue)} rel={orUndef(relValue)} {...rest}>
    {@render children?.()}
  </a>
{/if}
