<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  TableHeadCell renders th with optional scope and abbr.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type TableHeadCellProps = {
    scope?: string;
    colspan?: number;
    rowspan?: number;
    abbr?: string;
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { tableHeadCellClasses } from "./table.shared";
  import { isSetNum, oneOfOrLower, orUndef } from "../../utils/expr";

  let {
    scope,
    colspan: colSpan,
    rowspan: rowSpan,
    abbr,
    class: className,
    children,
    ...rest
  }: TableHeadCellProps = $props();

  const cls = $derived(tableHeadCellClasses({ className }));
</script>

<th {...(cls ? { class: cls } : {})} scope={orUndef(oneOfOrLower(scope, "", "col", "colgroup", "row", "rowgroup")) as "col" | "colgroup" | "row" | "rowgroup" | undefined} abbr={orUndef(abbr)} colspan={isSetNum(colSpan) ? colSpan : undefined} rowspan={isSetNum(rowSpan) ? rowSpan : undefined} {...rest}>
  {@render children?.()}
</th>
