export const copy = {
  skip: "Skip to content",
  logo: "LeX",
  nav: {
    home: "Home",
    slices: "Slices",
    playground: "Playground",
  },
  themeLight: "Use light theme",
  themeDark: "Use dark theme",
  project: "Project",
  importProject: "Import project",
  exportProject: "Export project",
  fileInput: "Project file",
  honeypot: "Company",
  home: {
    title: "Typed decisions, sealed and replayable",
    lead: "LeX is a typed-decision switch. A caller sends State and a QuestionSet. LeX pins the adapter, checks the raw answers, and returns a structural report with a replay bundle.",
    lines: [
      "evidence != judgment",
      "judgment != authority",
      "authority != execution",
      "execution != verified success",
    ],
    body: "Questions are Noul, Choice, or Score. LeX does not pick a threshold, a verdict, or a next action. This playground assembles that request. Run stays closed until the connections are drawn, and a short pause separates actions from the call.",
    github: "GitHub source",
    playground: "Playground",
  },
  slices: {
    title: "Vertical slices",
    lead: "Ten request shapes. Open a card to assemble its flow. Nothing is sent until the slice is complete.",
    open: "Open flow",
  },
  playground: {
    title: "Playground",
    json: "Request JSON",
    run: "Run",
    hideJson: "Hide JSON",
    showJson: "Show JSON",
    split: "Resize JSON",
    deleteEdge: "Delete connection",
    locked: "Run stays closed until every connection is drawn and the pause has elapsed.",
    composed: "Request composed on this page. The browser does not call the provider.",
    reasons: {
      "state-json": "State must be a JSON object.",
      "state-empty": "State needs at least one field.",
      questions: "Connect State to the question group and the group to Decision.",
      context: "Connect State to Context and Context to Decision.",
      output: "Connect Decision to the output.",
      "request-json": "Request JSON does not parse.",
      shape: "Request fields do not match this slice.",
      trap: "Request blocked.",
      dwell: "Flow is complete. Run waits for a short pause.",
      quiet: "Pause after the last edit before Run.",
      burst: "Actions arrived too close together.",
      lock: "Run is cooling down.",
      session: "Run waits until the page has been open for a moment.",
    },
  },
} as const;
